/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author yelbetto
 */
public class Buscaminas extends javax.swing.JFrame {

    Casilla[][] botones;
    boolean mostrar;
    int noBombas = 0;
    int encontradas = 0;

    /**
     * Creates new form BuscaminasFrame
     */
    public Buscaminas() {
        mostrar = false;
        initComponents();
        btnMarcar.setText("Marcar Mina \u2691");
        btnRevelar.setText("Revelar \u25C9");
    }

    public void perdiste(int id) {
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                if (botones[i][j].bomb) {
                    try {
                        if (botones[i][j].getId() == id) {
                            botones[i][j].cambiarIcono(Casilla.EXPLOTE, false);
                        } else {
                            botones[i][j].cambiarIcono(Casilla.BOMB, false);
                        }
                        botones[i][j].revelada = true;
                    } catch (IOException ex) {
                        Logger.getLogger(Buscaminas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }

    public void añadirBotones() {
        GridLayout gl = (GridLayout) pnlTablero.getLayout();
        gl.setColumns(botones[0].length);
        gl.setRows(botones.length);
        int casillaTamanio = (-5+(int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / botones.length)) * 2 / 3;
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                botones[i][j].tamanio = casillaTamanio;
                botones[i][j].setId((i * botones.length + j));
                botones[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        try {
                            Casilla boton = (Casilla) e.getSource();
                            if (mostrar) {
                                if (boton.bomb(botones)) {
                                    perdiste(boton.id);
                                }
                            } else {
                                if (boton.flag()) {
                                    encontradas++;
                                } else {
                                    encontradas--;
                                }
                                numeroBombas.setText("Bombas descubiertas: "+encontradas+"/" + noBombas+" 💣");
                            }
                        } catch (IOException ex) {
                            Logger.getLogger(Buscaminas.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                pnlTablero.add(botones[i][j]);
                pnlTablero.revalidate();
                pnlTablero.repaint();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlJuego = new javax.swing.JPanel();
        tituloBuscaminas = new javax.swing.JLabel();
        numeroBombas = new javax.swing.JLabel();
        pnlTablero = new javax.swing.JPanel();
        pnlOpciones = new javax.swing.JPanel();
        btnLeerAleatorio = new javax.swing.JButton();
        btnMarcar = new javax.swing.JButton();
        btnRevelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSCAMINAS");
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(new java.awt.Dimension(0, 0));

        pnlJuego.setLayout(new java.awt.GridBagLayout());

        tituloBuscaminas.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 24)); // NOI18N
        tituloBuscaminas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloBuscaminas.setText("Buscaminas");
        tituloBuscaminas.setMaximumSize(new java.awt.Dimension(100, 5));
        tituloBuscaminas.setMinimumSize(new java.awt.Dimension(100, 5));
        pnlJuego.add(tituloBuscaminas, new java.awt.GridBagConstraints());

        numeroBombas.setFont(new java.awt.Font("DejaVu Sans Light", 0, 10)); // NOI18N
        numeroBombas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlJuego.add(numeroBombas, gridBagConstraints);

        pnlTablero.setPreferredSize(new Dimension(((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight())) * 2 / 3,((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight())) * 2 / 3));
        pnlTablero.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlJuego.add(pnlTablero, gridBagConstraints);

        pnlOpciones.setLayout(new java.awt.GridLayout(1, 3));

        btnLeerAleatorio.setText("Leer archivo y obtener tablero aleatorio");
        btnLeerAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerAleatorioActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnLeerAleatorio);

        btnMarcar.setBackground(java.awt.Color.orange);
        btnMarcar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnMarcar.setForeground(new java.awt.Color(51, 51, 51));
        btnMarcar.setText("Marcar mina");
        btnMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnMarcar);

        btnRevelar.setBackground(new java.awt.Color(204, 0, 0));
        btnRevelar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnRevelar.setForeground(new java.awt.Color(255, 255, 255));
        btnRevelar.setText("Revelar");
        btnRevelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevelarActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnRevelar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlJuego.add(pnlOpciones, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeerAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerAleatorioActionPerformed
        File f;
        BufferedReader br = null;
        String cadena;
        f = new File("mar.txt");
        Tablero nuevo = null;
        int conteo = 0;
        if (f.exists()) {
            try {
                br = new BufferedReader(new FileReader(f));
                while ((cadena = br.readLine()) != null) {
                    if (cadena.contains("dimension")) {
                        String[] dim1 = cadena.split(" ");
                        String[] dimensiones = dim1[1].split("x");
                        nuevo = new Tablero(Integer.parseInt(dimensiones[0]), Integer.parseInt(dimensiones[1]));
                        nuevo.crearTableroVacio();
                        conteo = 0;
                    } else if (cadena.contains("bombasAleatorias") && nuevo != null) {
                        nuevo.setBombasAleatorias(true);
                        conteo = 0;
                    } else if (nuevo != null) {
                        nuevo.agregarLinea(cadena, conteo);
                        conteo++;
                    }
                }
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        } else {
            System.out.println("Archivo inexistente");
        }
        botones = nuevo.getCasillas();
        noBombas = nuevo.getNumeroBombas();
        numeroBombas.setText("Bombas descubiertas: 0/" + noBombas+"  💣");
        añadirBotones();
        btnMarcar.setEnabled(false);
        btnRevelar.setEnabled(true);
    }//GEN-LAST:event_btnLeerAleatorioActionPerformed

    private void btnRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevelarActionPerformed
        mostrar = true;
        btnMarcar.setEnabled(true);
        btnRevelar.setEnabled(false);
    }//GEN-LAST:event_btnRevelarActionPerformed

    private void btnMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarActionPerformed
        mostrar = false;
        btnMarcar.setEnabled(false);
        btnRevelar.setEnabled(true);
    }//GEN-LAST:event_btnMarcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscaminas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeerAleatorio;
    private javax.swing.JButton btnMarcar;
    private javax.swing.JButton btnRevelar;
    private javax.swing.JLabel numeroBombas;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JLabel tituloBuscaminas;
    // End of variables declaration//GEN-END:variables
}
