/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author yelbetto
 */
public class EditorBuscaminas extends javax.swing.JFrame {

    Casilla[][] botones;
    int dimensionx = 5;
    int dimensiony = 5;

    /**
     * Creates new form BuscaminasFrame
     */
    public EditorBuscaminas() {
        initComponents();
        añadirBotones();
    }

    public void añadirBotones() {
        botones = new Casilla[dimensiony][dimensionx];
        GridLayout gl = (GridLayout) pnlTablero.getLayout();
        gl.setColumns(botones[0].length);
        gl.setRows(botones.length);
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones[i].length; j++) {
                try {
                    botones[i][j] = new Casilla(-5 +((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight() / botones.length)) * 2 / 3);
                    botones[i][j].setId((i * botones.length + j));
                    botones[i][j].addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            try {
                                Casilla boton = (Casilla) e.getSource();
                                boton.bomb = !boton.bomb;
                                if (boton.bomb) {
                                    boton.cambiarIcono(Casilla.BOMB, false);
                                } else {
                                    boton.cambiarIcono(Casilla.WATER, false);
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(EditorBuscaminas.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });
                    pnlTablero.add(botones[i][j]);
                    pnlTablero.revalidate();
                    pnlTablero.repaint();
                } catch (IOException ex) {
                    Logger.getLogger(EditorBuscaminas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlEditorTablero = new javax.swing.JPanel();
        lblEditorTableros = new javax.swing.JLabel();
        lblInfoEditor = new javax.swing.JLabel();
        pnlTablero = new javax.swing.JPanel();
        btnCrearArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        pnlEditorTablero.setLayout(new java.awt.GridBagLayout());

        lblEditorTableros.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 24)); // NOI18N
        lblEditorTableros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEditorTableros.setText("Editor de tableros del buscaminas");
        lblEditorTableros.setMaximumSize(new java.awt.Dimension(100, 5));
        lblEditorTableros.setMinimumSize(new java.awt.Dimension(100, 5));
        pnlEditorTablero.add(lblEditorTableros, new java.awt.GridBagConstraints());

        lblInfoEditor.setFont(new java.awt.Font("DejaVu Sans Light", 0, 10)); // NOI18N
        lblInfoEditor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInfoEditor.setText("Dale click a la casilla donde quieras que haya una bomba");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnlEditorTablero.add(lblInfoEditor, gridBagConstraints);

        pnlTablero.setPreferredSize(new Dimension(((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight())) * 2 / 3,((int) (Toolkit.getDefaultToolkit().getScreenSize().getHeight())) * 2 / 3));
        pnlTablero.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlEditorTablero.add(pnlTablero, gridBagConstraints);

        btnCrearArchivo.setText("Crear archivo");
        btnCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearArchivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnlEditorTablero.add(btnCrearArchivo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditorTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditorTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearArchivoActionPerformed
        String[] lineas = new String[botones.length];
        for (int i = 0; i < botones.length; i++) {
            lineas[i] = "";
            for (int j = 0; j < botones[i].length; j++) {
                lineas[i] += (botones[i][j].bomb) ? "O" : "~";
                if (j != (botones[i].length - 1)) {
                    lineas[i] += ",";
                }
            }
        }
        File f;
        PrintWriter escritor = null;
        f = new File("mar.txt");
        try {
            escritor = new PrintWriter(new DataOutputStream(new FileOutputStream(f, false)));
            escritor.println("TABLEROS");
            escritor.println("dimension " + dimensionx + "x" + dimensiony);
            for (int i = 0; i < lineas.length; i++) {
                String linea = lineas[i];
                escritor.println(linea);
            }
            JOptionPane.showMessageDialog(null, "Se ha creado correctamente el archivo");
            escritor.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCrearArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorBuscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorBuscaminas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearArchivo;
    private javax.swing.JLabel lblEditorTableros;
    private javax.swing.JLabel lblInfoEditor;
    private javax.swing.JPanel pnlEditorTablero;
    private javax.swing.JPanel pnlTablero;
    // End of variables declaration//GEN-END:variables
}
